# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

begin
  load "heroku_tool/lib/tasks/db_drop_all_tables.rake"
rescue LoadError
  # not loading db_drop_all_tables -- not defined in this environment?
end
